language: generic
env: SWIFT_VERSION=4.2-DEVELOPMENT-SNAPSHOT-2018-06-04-a

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
    - os: osx
      osx_image: xcode9.2

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - make
  - make test
